# Generated by Django 5.0.1 on 2024-05-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_adress1_shippingaddress_shipping_adress1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_adress2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
